packages:
  - apps/*
  - packages/*
catalog:
  dotenv: ^17.2.2
  zod: ^4.1.13
  typescript: ^5
  "@types/node": ^22.13.14
  "@trpc/server": ^11.7.2
  better-auth: ^1.4.18
  "@types/express": ^5.0.1
  "@prisma/client": ^7.2.0
  "@trpc/client": ^11.7.2
